### ISSUE TITLE
Use filter

### ISSUE THREAD

**Issue by ernest-czol** [LeCezar/GarminAcademyAndroid2021#1]
https://github.com/LeCezar/GarminAcademyAndroid2021/blob/0b90a06768bb9678f428cdd47d7434453e743ca7/Homework/KotlinBasics/src/main/kotlin/exercise5/Main.kt#L30

You can use the filter utility function for this purpose.

**Comment by LeCezar** [comment]
Yes i thought about that, but I figured using "filter" then using "forEach"
for printing would be more inefficient.

**Comment by ernest-czol** [comment]
You're right. If you want to print just the values you would need a combination between map and filter. You can achieve something like that:
println(data.mapNotNull { it.takeIf { it.value > 100 }?.value })

**Comment by LeCezar** [comment]
Didn't think about this, thanks for the tip :)
